apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-config-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /var/lib/adguardhome-config
    type: DirectoryOrCreate
