apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /var/lib/adguardhome
    type: DirectoryOrCreate
  # NOTE: hostPath PVs are suitable for single-node or test clusters. For multi-node clusters
  # either add nodeAffinity below or deploy a dynamic provisioner (e.g. local-path-provisioner, OpenEBS).
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - YOUR_NODE_NAME
